/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./components/settings/AboutTab.vue')['default']
    AppShell: typeof import('./components/shell/AppShell.vue')['default']
    CaptureTab: typeof import('./components/settings/CaptureTab.vue')['default']
    CommandPalette: typeof import('./components/shell/CommandPalette.vue')['default']
    ConnectionTab: typeof import('./components/settings/ConnectionTab.vue')['default']
    DiagnosisPanel: typeof import('./components/player/DiagnosisPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    PlayerShell: typeof import('./components/player/PlayerShell.vue')['default']
    RecordControls: typeof import('./components/live/RecordControls.vue')['default']
    ReplayGrid: typeof import('./components/player/ReplayGrid.vue')['default']
    RetentionTab: typeof import('./components/settings/RetentionTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionCard: typeof import('./components/sessions/SessionCard.vue')['default']
    SessionFilters: typeof import('./components/sessions/SessionFilters.vue')['default']
    SessionList: typeof import('./components/sessions/SessionList.vue')['default']
    SideNav: typeof import('./components/shell/SideNav.vue')['default']
    SkeletonList: typeof import('./components/common/SkeletonList.vue')['default']
    SourceRack: typeof import('./components/live/SourceRack.vue')['default']
    StatusDot: typeof import('./components/common/StatusDot.vue')['default']
    TenantDetail: typeof import('./components/tenants/TenantDetail.vue')['default']
    TenantList: typeof import('./components/tenants/TenantList.vue')['default']
    Timeline: typeof import('./components/player/Timeline.vue')['default']
    TopBar: typeof import('./components/shell/TopBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
